export const TEAM_SCHEMA_VERSION = 24

export const requiredTeamTableNames = [
  'team_schema_migrations',
  'schema_meta',
  'organizations',
  'users',
  'auth_accounts',
  'desktop_pairing_codes',
  'desktop_tokens',
  'projects',
  'project_members',
  'workflow_runs',
  'workflow_nodes',
  'workflow_edges',
  'artifacts',
  'agent_events',
  'test_evidence_summaries',
  'mcp_server_definitions',
  'skills',
  'token_usage',
  'agent_provider_credentials',
  'agent_reviews',
  'agent_traces',
  'agent_token_usage',
  'coding_agent_summaries',
  'agent_runtime_summaries',
  'agent_runtime_projection_audits',
  'agent_memory_summaries',
  'agent_memory_projection_audits',
  'agent_coordination_summaries',
  'agent_coordination_projection_audits',
  'enforcement_policies',
  'gate_override_decisions',
  'runtime_budget_policies',
  'runtime_budget_approvals',
  'agent_policy_findings',
  'work_requests',
  'collaboration_idempotency',
  'collaboration_audit_events',
  'gate_commands',
  'gate_command_receipts',
  'gate_command_acknowledgements',
  'released_work_request_claims',
  'github_repository_bindings',
  'github_delivery_requests',
  'github_delivery_approvals',
  'github_delivery_credential_grants',
  'github_branch_publications',
  'github_pull_request_outcomes',
] as const

export type TeamTableName = (typeof requiredTeamTableNames)[number]

export type TeamColumnDefinition = {
  name: string
  sqlType: string
  nullable: boolean
  primaryKey?: boolean
  references?: string
}

export type TeamTableDefinition = {
  name: TeamTableName
  columns: TeamColumnDefinition[]
}

function column(
  name: string,
  sqlType: string,
  options: {
    nullable?: boolean
    primaryKey?: boolean
    references?: string
  } = {},
): TeamColumnDefinition {
  const definition: TeamColumnDefinition = {
    name,
    sqlType,
    nullable: options.nullable ?? false,
  }

  if (options.primaryKey !== undefined) {
    definition.primaryKey = options.primaryKey
  }

  if (options.references !== undefined) {
    definition.references = options.references
  }

  return definition
}

export const teamTableDefinitions: TeamTableDefinition[] = [
  {
    name: 'team_schema_migrations',
    columns: [
      column('version', 'integer', { primaryKey: true }),
      column('name', 'text'),
      column('checksum', 'text'),
      column('adopted', 'boolean'),
      column('applied_at', 'timestamptz'),
    ],
  },
  {
    name: 'schema_meta',
    columns: [
      column('key', 'text', { primaryKey: true }),
      column('value', 'text'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'organizations',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('name', 'text'),
      column('slug', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'users',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('name', 'text'),
      column('email', 'text', { nullable: true }),
      column('avatar_url', 'text', { nullable: true }),
      column('role', 'text'),
      column('avatar_initials', 'text'),
      column('focus', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'auth_accounts',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('user_id', 'text', { references: 'users.id' }),
      column('provider', 'text'),
      column('provider_account_id', 'text'),
      column('username', 'text', { nullable: true }),
      column('email', 'text', { nullable: true }),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'desktop_pairing_codes',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('created_by_user_id', 'text', { references: 'users.id' }),
      column('issued_role', 'text'),
      column('code_hash', 'text'),
      column('expires_at', 'timestamptz'),
      column('consumed_at', 'timestamptz', { nullable: true }),
      column('revoked_at', 'timestamptz', { nullable: true }),
      column('failed_attempts', 'integer'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'desktop_tokens',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('user_id', 'text', { references: 'users.id' }),
      column('issued_role', 'text'),
      column('token_hash', 'text'),
      column('created_at', 'timestamptz'),
      column('expires_at', 'timestamptz'),
      column('last_used_at', 'timestamptz', { nullable: true }),
      column('revoked_at', 'timestamptz', { nullable: true }),
    ],
  },
  {
    name: 'projects',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('name', 'text'),
      column('slug', 'text'),
      column('description', 'text'),
      column('repository', 'text'),
      column('default_branch', 'text'),
      column('health', 'text'),
      column('knowledge_base_path', 'text'),
      column('test_command', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'project_members',
    columns: [
      column('project_id', 'text', { primaryKey: true, references: 'projects.id' }),
      column('user_id', 'text', { primaryKey: true, references: 'users.id' }),
      column('role', 'text'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'workflow_runs',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_version', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('creator_id', 'text', { references: 'users.id' }),
      column('data_origin', 'text'),
      column('title', 'text'),
      column('request', 'text'),
      column('status', 'text'),
      column('current_node_id', 'text'),
      column('branch_name', 'text'),
      column('pull_request_url', 'text', { nullable: true }),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'workflow_nodes',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('stage', 'text'),
      column('title', 'text'),
      column('subtitle', 'text'),
      column('kind', 'text'),
      column('status', 'text'),
      column('owner_id', 'text', { references: 'users.id' }),
      column('required_role', 'text', { nullable: true }),
      column('retry_count', 'integer'),
      column('token_usage_id', 'text', { nullable: true }),
      column('position', 'integer'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'workflow_edges',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('source_node_id', 'text', { references: 'workflow_nodes.id' }),
      column('target_node_id', 'text', { references: 'workflow_nodes.id' }),
      column('kind', 'text'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'artifacts',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('kind', 'text'),
      column('title', 'text'),
      column('summary', 'text'),
      column('content', 'text'),
      column('redacted', 'boolean'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_events',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { nullable: true, references: 'workflow_nodes.id' }),
      column('sequence', 'integer'),
      column('kind', 'text'),
      column('message', 'text'),
      column('timestamp', 'timestamptz'),
    ],
  },
  {
    name: 'test_evidence_summaries',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('command', 'text'),
      column('status', 'text'),
      column('exit_code', 'integer', { nullable: true }),
      column('duration_ms', 'integer'),
      column('summary', 'text'),
      column('redacted', 'boolean'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'mcp_server_definitions',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('name', 'text'),
      column('command', 'text'),
      column('permission', 'text'),
      column('enabled_by_default', 'boolean'),
      column('last_audit_event', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'skills',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('name', 'text'),
      column('stage', 'text'),
      column('description', 'text'),
      column('version', 'text'),
      column('enabled', 'boolean'),
      column('source', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'token_usage',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('user_id', 'text', { references: 'users.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('provider', 'text'),
      column('model', 'text'),
      column('input_tokens', 'integer'),
      column('output_tokens', 'integer'),
      column('cache_read_tokens', 'integer'),
      column('cost_usd', 'numeric(12,6)'),
      column('timestamp', 'timestamptz'),
    ],
  },
  {
    name: 'agent_provider_credentials',
    columns: [
      column('organization_id', 'text', { primaryKey: true, references: 'organizations.id' }),
      column('provider_id', 'text', { primaryKey: true }),
      column('provider_name', 'text'),
      column('model', 'text'),
      column('base_url', 'text', { nullable: true }),
      column('masked_credential', 'text'),
      column('encrypted_secret', 'text'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_reviews',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('request_id', 'text'),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('runtime', 'text'),
      column('provider_id', 'text'),
      column('model', 'text'),
      column('conclusion', 'text'),
      column('summary', 'text'),
      column('risks', 'jsonb'),
      column('missing_evidence', 'jsonb'),
      column('suggested_tests', 'jsonb'),
      column('knowledge_references', 'jsonb'),
      column('policy_findings', 'jsonb'),
      column('confidence', 'numeric(4,3)'),
      column('gate_advisory', 'jsonb'),
      column('context_manifest', 'jsonb', { nullable: true }),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_traces',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('review_id', 'text', { references: 'agent_reviews.id' }),
      column('runtime', 'text'),
      column('steps', 'jsonb'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_token_usage',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('user_id', 'text', { references: 'users.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('provider', 'text'),
      column('model', 'text'),
      column('input_tokens', 'integer'),
      column('output_tokens', 'integer'),
      column('cache_read_tokens', 'integer'),
      column('cost_usd', 'numeric(12,6)'),
      column('timestamp', 'timestamptz'),
      column('source', 'text'),
    ],
  },
  {
    name: 'coding_agent_summaries',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text'),
      column('project_id', 'text', { references: 'projects.id' }),
      column('requested_by', 'text', { references: 'users.id' }),
      column('provider_id', 'text'),
      column('engine', 'text'),
      column('status', 'text'),
      column('branch_name', 'text'),
      column('summary', 'text'),
      column('changed_paths', 'jsonb'),
      column('started_at', 'timestamptz'),
      column('completed_at', 'timestamptz', { nullable: true }),
      column('cost_provider', 'text', { nullable: true }),
      column('cost_model', 'text', { nullable: true }),
      column('cost_input_tokens', 'integer', { nullable: true }),
      column('cost_output_tokens', 'integer', { nullable: true }),
      column('cost_cache_read_tokens', 'integer', { nullable: true }),
      column('cost_usd', 'numeric(12,6)', { nullable: true }),
      column('cost_source', 'text', { nullable: true }),
      column('redacted', 'boolean'),
    ],
  },
  {
    name: 'agent_runtime_summaries',
    columns: [
      column('runtime_id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('state_version', 'integer'),
      column('projection_version', 'integer'),
      column('runtime_version', 'integer'),
      column('checkpoint_version', 'integer'),
      column('status', 'text'),
      column('stop_reason', 'text', { nullable: true }),
      column('steps', 'bigint'),
      column('tool_calls', 'bigint'),
      column('tokens', 'bigint'),
      column('cost_usd', 'numeric(18,6)'),
      column('accepted_action_count', 'bigint'),
      column('context_digest', 'text'),
      column('capability_set_digest', 'text'),
      column('last_observation_digest', 'text'),
      column('last_result_digest', 'text', { nullable: true }),
      column('summary_digest', 'text'),
      column('started_at', 'timestamptz'),
      column('runtime_updated_at', 'timestamptz'),
      column('redacted', 'boolean'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_runtime_projection_audits',
    columns: [
      column('runtime_id', 'text', { references: 'agent_runtime_summaries.runtime_id' }),
      column('runtime_version', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('summary_digest', 'text'),
      column('submitted_by_user_id', 'text', { references: 'users.id' }),
      column('desktop_token_id', 'text', { nullable: true, references: 'desktop_tokens.id' }),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_memory_summaries',
    columns: [
      column('memory_id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('runtime_id', 'text'),
      column('owner_user_id', 'text', { references: 'users.id' }),
      column('candidate_id', 'text'),
      column('state_version', 'integer'),
      column('projection_version', 'integer'),
      column('current_revision', 'integer'),
      column('head_version', 'integer'),
      column('quality_version', 'bigint'),
      column('lifecycle_status', 'text'),
      column('visibility', 'text'),
      column('sensitivity', 'text'),
      column('retention_class', 'text'),
      column('provenance_digest', 'text'),
      column('citation_ids', 'jsonb'),
      column('retrieval_count', 'bigint'),
      column('accepted_context_count', 'bigint'),
      column('expires_at', 'timestamptz', { nullable: true }),
      column('deleted_at', 'timestamptz', { nullable: true }),
      column('purge_status', 'text', { nullable: true }),
      column('purged_at', 'timestamptz', { nullable: true }),
      column('memory_updated_at', 'timestamptz'),
      column('projection_digest', 'text'),
      column('redacted', 'boolean'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_memory_projection_audits',
    columns: [
      column('memory_id', 'text', { references: 'agent_memory_summaries.memory_id' }),
      column('head_version', 'integer'),
      column('quality_version', 'bigint'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('runtime_id', 'text'),
      column('projection_digest', 'text'),
      column('submitted_by_user_id', 'text', { references: 'users.id' }),
      column('desktop_token_id', 'text', { nullable: true, references: 'desktop_tokens.id' }),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_coordination_summaries',
    columns: [
      column('coordination_id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('state_version', 'integer'),
      column('projection_version', 'integer'),
      column('coordination_version', 'integer'),
      column('graph_version', 'integer'),
      column('status', 'text'),
      column('stop_reason', 'text', { nullable: true }),
      column('role_counts', 'jsonb'),
      column('task_status_counts', 'jsonb'),
      column('failure_category_counts', 'jsonb'),
      column('task_count', 'bigint'),
      column('edge_count', 'bigint'),
      column('specialist_starts', 'bigint'),
      column('accepted_handoff_count', 'bigint'),
      column('retry_count', 'bigint'),
      column('step_count', 'bigint'),
      column('tool_call_count', 'bigint'),
      column('token_count', 'bigint'),
      column('cost_usd', 'numeric(18,6)'),
      column('single_agent_quality', 'numeric(7,6)', { nullable: true }),
      column('coordination_quality', 'numeric(7,6)', { nullable: true }),
      column('latency_ms', 'bigint'),
      column('human_intervention_count', 'bigint'),
      column('authority_violation_count', 'bigint'),
      column('isolation_violation_count', 'bigint'),
      column('termination_violation_count', 'bigint'),
      column('replay_violation_count', 'bigint'),
      column('redaction_violation_count', 'bigint'),
      column('coordination_updated_at', 'timestamptz'),
      column('isolated', 'boolean'),
      column('redacted', 'boolean'),
      column('summary_digest', 'text'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_coordination_projection_audits',
    columns: [
      column('coordination_id', 'text', { references: 'agent_coordination_summaries.coordination_id' }),
      column('coordination_version', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('summary_digest', 'text'),
      column('submitted_by_user_id', 'text', { references: 'users.id' }),
      column('desktop_token_id', 'text', { nullable: true, references: 'desktop_tokens.id' }),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'enforcement_policies',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { nullable: true, references: 'projects.id' }),
      column('name', 'text'),
      column('version', 'integer'),
      column('policy', 'jsonb'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'gate_override_decisions',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('user_id', 'text', { references: 'users.id' }),
      column('role', 'text'),
      column('reason', 'text'),
      column('blocked_reason_ids', 'jsonb'),
      column('policy_version', 'integer'),
      column('provisional', 'boolean'),
      column('status', 'text'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'runtime_budget_policies',
    columns: [
      column('project_id', 'text', { primaryKey: true, references: 'projects.id' }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('enabled', 'boolean'),
      column('monthly_limit_usd', 'numeric(12,6)'),
      column('warning_threshold_usd', 'numeric(12,6)'),
      column('currency', 'text'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'runtime_budget_approvals',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('requested_by', 'text', { references: 'users.id' }),
      column('approved_by', 'text', { references: 'users.id' }),
      column('role', 'text'),
      column('provider_id', 'text'),
      column('max_additional_cost_usd', 'numeric(12,6)'),
      column('reason', 'text'),
      column('status', 'text'),
      column('created_at', 'timestamptz'),
      column('expires_at', 'timestamptz'),
    ],
  },
  {
    name: 'agent_policy_findings',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('review_id', 'text', { references: 'agent_reviews.id' }),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('node_id', 'text', { references: 'workflow_nodes.id' }),
      column('category', 'text'),
      column('severity', 'text'),
      column('summary', 'text'),
      column('evidence_ids', 'jsonb'),
      column('knowledge_reference_ids', 'jsonb'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'work_requests',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('title', 'text'),
      column('request', 'text'),
      column('version', 'integer'),
      column('status', 'text'),
      column('created_by_user_id', 'text', { references: 'users.id' }),
      column('claimed_by_token_id', 'text', {
        nullable: true,
        references: 'desktop_tokens.id',
      }),
      column('claimed_run_id', 'text', { nullable: true }),
      column('claimed_at', 'timestamptz', { nullable: true }),
      column('materialized_at', 'timestamptz', { nullable: true }),
      column('expires_at', 'timestamptz', { nullable: true }),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'collaboration_idempotency',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('actor_user_id', 'text', { references: 'users.id' }),
      column('auth_kind', 'text'),
      column('auth_token_record_id', 'text', { nullable: true }),
      column('operation_kind', 'text'),
      column('idempotency_key', 'text'),
      column('request_fingerprint', 'text'),
      column('response_status', 'integer'),
      column('outcome_code', 'text'),
      column('response_json', 'jsonb'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'collaboration_audit_events',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('actor_user_id', 'text', { references: 'users.id' }),
      column('actor_role', 'text'),
      column('auth_kind', 'text'),
      column('auth_token_record_id', 'text', { nullable: true }),
      column('record_kind', 'text'),
      column('record_id', 'text'),
      column('action', 'text'),
      column('expected_version', 'integer', { nullable: true }),
      column('observed_version', 'integer', { nullable: true }),
      column('outcome_code', 'text'),
      column('request_fingerprint', 'text'),
      column('details', 'jsonb'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'gate_commands',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('version', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('work_request_id', 'text', {
        nullable: true,
        references: 'work_requests.id',
      }),
      column('run_id', 'text'),
      column('node_id', 'text'),
      column('action', 'text'),
      column('workflow_command', 'text', { nullable: true }),
      column('reason', 'text'),
      column('requested_by_user_id', 'text', { references: 'users.id' }),
      column('requested_role', 'text'),
      column('auth_kind', 'text'),
      column('auth_token_record_id', 'text', { nullable: true }),
      column('idempotency_key', 'text'),
      column('request_fingerprint', 'text'),
      column('expected_run_version', 'integer'),
      column('expected_policy_version', 'integer'),
      column('expected_blocker_ids', 'jsonb'),
      column('evaluation_status', 'text'),
      column('evaluation_blocker_ids', 'jsonb'),
      column('evaluated_at', 'timestamptz'),
      column('status', 'text'),
      column('outcome_code', 'text', { nullable: true }),
      column('expires_at', 'timestamptz'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'gate_command_receipts',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('command_id', 'text', { references: 'gate_commands.id' }),
      column('attempt', 'integer'),
      column('leased_to_token_id', 'text', { references: 'desktop_tokens.id' }),
      column('leased_at', 'timestamptz'),
      column('lease_expires_at', 'timestamptz'),
      column('acknowledged_at', 'timestamptz', { nullable: true }),
    ],
  },
  {
    name: 'gate_command_acknowledgements',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('command_id', 'text', { references: 'gate_commands.id' }),
      column('receipt_id', 'text', { references: 'gate_command_receipts.id' }),
      column('outcome_code', 'text'),
      column('before_run_version', 'integer'),
      column('after_run_version', 'integer'),
      column('evaluated_at', 'timestamptz'),
      column('created_at', 'timestamptz'),
    ],
  },
  {
    name: 'released_work_request_claims',
    columns: [
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('work_request_id', 'text', { references: 'work_requests.id' }),
      column('run_id', 'text'),
      column('claimed_by_token_id', 'text', { references: 'desktop_tokens.id' }),
      column('released_by_user_id', 'text', { references: 'users.id' }),
      column('released_claim_version', 'integer'),
      column('released_at', 'timestamptz'),
    ],
  },
  {
    name: 'github_repository_bindings',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('version', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('installation_id', 'text'),
      column('repository_id', 'text'),
      column('full_name', 'text'),
      column('default_branch', 'text'),
      column('status', 'text'),
      column('configured_by_user_id', 'text', { references: 'users.id' }),
      column('updated_by_user_id', 'text', { references: 'users.id' }),
      column('validated_at', 'timestamptz'),
      column('revoked_at', 'timestamptz', { nullable: true }),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'github_delivery_requests',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('state_version', 'integer'),
      column('intent_revision', 'integer'),
      column('organization_id', 'text', { references: 'organizations.id' }),
      column('project_id', 'text', { references: 'projects.id' }),
      column('requested_by_user_id', 'text', { references: 'users.id' }),
      column('requested_by_token_id', 'text', { references: 'desktop_tokens.id' }),
      column('local_intent_id', 'text'),
      column('local_project_id', 'text'),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('run_version', 'integer'),
      column('node_id', 'text'),
      column('binding_id', 'text', { references: 'github_repository_bindings.id' }),
      column('binding_version', 'integer'),
      column('installation_id', 'text'),
      column('repository_id', 'text'),
      column('repository_full_name', 'text'),
      column('coding_run_id', 'text'),
      column('workspace_id', 'text'),
      column('diff_artifact_id', 'text'),
      column('test_evidence_id', 'text'),
      column('pr_package_artifact_id', 'text'),
      column('status', 'text'),
      column('outcome_code', 'text', { nullable: true }),
      column('expected_run_version', 'integer'),
      column('base_branch', 'text'),
      column('head_branch', 'text'),
      column('base_commit_sha', 'text'),
      column('expected_commit_sha', 'text'),
      column('intent_digest', 'text'),
      column('delivery_series_key', 'text'),
      column('delivery_attempt', 'integer'),
      column('logical_idempotency_key', 'text'),
      column('diff_digest', 'text'),
      column('test_evidence_digest', 'text'),
      column('package_digest', 'text'),
      column('changed_paths', 'jsonb'),
      column('pr_title', 'text'),
      column('pr_body', 'text'),
      column('expires_at', 'timestamptz'),
      column('created_at', 'timestamptz'),
      column('updated_at', 'timestamptz'),
    ],
  },
  {
    name: 'github_delivery_approvals',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('request_id', 'text', { references: 'github_delivery_requests.id' }),
      column('intent_revision', 'integer'),
      column('request_state_version', 'integer'),
      column('intent_digest', 'text'),
      column('binding_id', 'text', { references: 'github_repository_bindings.id' }),
      column('binding_version', 'integer'),
      column('run_id', 'text', { references: 'workflow_runs.id' }),
      column('run_version', 'integer'),
      column('node_id', 'text'),
      column('repository_id', 'text'),
      column('base_branch', 'text'),
      column('head_branch', 'text'),
      column('expected_commit_sha', 'text'),
      column('test_evidence_digest', 'text'),
      column('package_digest', 'text'),
      column('approved_by_user_id', 'text', { references: 'users.id' }),
      column('approved_role', 'text'),
      column('auth_kind', 'text'),
      column('approved_at', 'timestamptz'),
    ],
  },
  {
    name: 'github_delivery_credential_grants',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('version', 'integer'),
      column('request_id', 'text', { references: 'github_delivery_requests.id' }),
      column('intent_revision', 'integer'),
      column('approval_id', 'text', { references: 'github_delivery_approvals.id' }),
      column('attempt', 'integer'),
      column('issued_to_token_id', 'text', { references: 'desktop_tokens.id' }),
      column('repository_id', 'text'),
      column('permission', 'text'),
      column('repository_count', 'integer'),
      column('status', 'text'),
      column('requested_at', 'timestamptz'),
      column('issued_at', 'timestamptz', { nullable: true }),
      column('credential_expires_at', 'timestamptz', { nullable: true }),
      column('provider_expiry_contract_version', 'smallint'),
      column('provider_credential_expires_at', 'timestamptz', { nullable: true }),
      column('provider_expiry_observed_at', 'timestamptz', { nullable: true }),
      column('consumed_at', 'timestamptz', { nullable: true }),
      column('outcome_code', 'text', { nullable: true }),
    ],
  },
  {
    name: 'github_branch_publications',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('version', 'integer'),
      column('request_id', 'text', { references: 'github_delivery_requests.id' }),
      column('intent_revision', 'integer'),
      column('grant_id', 'text', {
        nullable: true,
        references: 'github_delivery_credential_grants.id',
      }),
      column('source_publication_id', 'text', {
        nullable: true,
        references: 'github_branch_publications.id',
      }),
      column('status', 'text'),
      column('reported_outcome_code', 'text'),
      column('verified_head_sha', 'text', { nullable: true }),
      column('reported_at', 'timestamptz'),
      column('verified_at', 'timestamptz', { nullable: true }),
      column('outcome_code', 'text', { nullable: true }),
    ],
  },
  {
    name: 'github_pull_request_outcomes',
    columns: [
      column('id', 'text', { primaryKey: true }),
      column('version', 'integer'),
      column('request_id', 'text', { references: 'github_delivery_requests.id' }),
      column('intent_revision', 'integer'),
      column('publication_id', 'text', { references: 'github_branch_publications.id' }),
      column('status', 'text'),
      column('pull_request_id', 'text', { nullable: true }),
      column('pull_request_number', 'integer', { nullable: true }),
      column('safe_url', 'text', { nullable: true }),
      column('draft', 'boolean'),
      column('head_branch', 'text'),
      column('base_branch', 'text'),
      column('head_sha', 'text'),
      column('provider_created_at', 'timestamptz', { nullable: true }),
      column('provider_retry_not_before', 'timestamptz', { nullable: true }),
      column('recorded_at', 'timestamptz'),
      column('outcome_code', 'text', { nullable: true }),
    ],
  },
]
