import {describe,it,expect,vi} from 'vitest'
import {buildAgentReviewContext,createOpenAiCompatibleAgentProvider,runKnowledgeReviewAgent} from './agent-review'
import {runs,artifacts} from './fixtures'
async function context(){const run=runs[0]!;const node=run.nodes.find(n=>n.kind==='gate')!;return {context:await buildAgentReviewContext({run,node,artifacts,testEvidence:[],knowledgeDocuments:[],knowledgeChunks:[]}),request:{id:'failure-contract',runId:run.id,nodeId:node.id,projectId:run.projectId,requestedBy:'u',runtime:'electron' as const}}}
const review={conclusion:'建议通过',summary:'完整结论',risks:[],missingEvidence:[],suggestedTests:[],confidence:.8}
describe('review output and attempt accounting (#166)',()=>{
 it.each(['length','content_filter','insufficient_system_resource'])('records billed usage before rejecting finish_reason %s',async(reason)=>{const onAttemptUsage=vi.fn();const provider=createOpenAiCompatibleAgentProvider({apiKey:'fixture',model:'gpt-4.1-mini',fetcher:async()=>Response.json({choices:[{message:{content:JSON.stringify(review)},finish_reason:reason}],usage:{prompt_tokens:99,completion_tokens:2048}})});await expect(runKnowledgeReviewAgent({...await context(),provider,onAttemptUsage})).rejects.toMatchObject({usage:{inputTokens:99,outputTokens:2048}});expect(onAttemptUsage).toHaveBeenCalledOnce();expect(onAttemptUsage.mock.calls[0]![0]).toMatchObject({inputTokens:99,outputTokens:2048})})
 it('allows a valid response well beyond 2048 tokens with no implicit request cap',async()=>{let body:Record<string,unknown>={};const provider=createOpenAiCompatibleAgentProvider({apiKey:'fixture',model:'gpt-4.1-mini',fetcher:async(_url,init)=>{body=JSON.parse(String(init?.body));return Response.json({choices:[{message:{content:JSON.stringify({...review,summary:'核验结论。'.repeat(2100)})},finish_reason:'stop'}],usage:{prompt_tokens:100,completion_tokens:8000}})}});const result=await runKnowledgeReviewAgent({...await context(),provider});expect(body).not.toHaveProperty('max_tokens');expect(result.review.summary.length).toBeGreaterThan(5000);expect(result.tokenUsage.outputTokens).toBe(8000)})
 it('records schema failure with known usage while keeping absent usage unknown',async()=>{for(const usage of [{prompt_tokens:10,completion_tokens:20},undefined]){const onAttemptUsage=vi.fn();const provider=createOpenAiCompatibleAgentProvider({apiKey:'fixture',model:'gpt-4.1-mini',fetcher:async()=>Response.json({choices:[{message:{content:'{"summary":"incomplete"}'},finish_reason:'stop'}],...(usage?{usage}:{})})});await expect(runKnowledgeReviewAgent({...await context(),provider,onAttemptUsage})).rejects.toMatchObject({code:'invalid_model_output'});expect(onAttemptUsage).toHaveBeenCalledOnce();expect(onAttemptUsage.mock.calls[0]![0].costUsd===null).toBe(!usage)}})
})
