import {afterEach,describe,expect,it,vi} from 'vitest'
import {projectedModelCallCost,type ModelCallQuote,modelCallBudgetRollup,parseModelCallSettlement} from '@ai-devflow/shared'
import {createSeedTeamRepository} from './team-repository'
const context={organizationId:'org-demo',userId:'u-ling'}
const now='2026-09-23T18:00:00.000Z'
const quote=(id:string):ModelCallQuote=>({id,projectId:'p-payments',providerId:'deepseek',model:'deepseek-flash',createdAt:now,inputTokens:1000,maxOutputTokens:1000,billingProvider:'deepseek'})
async function setup(limit=50){vi.useFakeTimers();vi.setSystemTime(now);const repo=createSeedTeamRepository();await repo.saveRuntimeBudgetPolicy({projectId:'p-payments',enabled:true,monthlyLimitUsd:limit,warningThresholdUsd:limit*.8,currency:'USD',updatedAt:now},context);return repo}
afterEach(()=>vi.useRealTimers())
describe('atomic per-call model budget',()=>{
 it('persists a received result for recovery without publishing a provisional dispatch marker',async()=>{
  const repo=await setup();const priorTokens=(await repo.getTeamOverview(context)).projectCost.find(r=>r.key==='p-payments')?.totalTokens??0;await repo.reserveModelCall(quote('queued'),context)
  await repo.persistModelCallSettlement({id:'queued',projectId:'p-payments',state:'failed'},context)
  expect(await repo.listPendingModelCallSettlements('p-payments',context)).toEqual([])
  const result={id:'queued',projectId:'p-payments',state:'completed' as const,usage:{inputTokens:100,outputTokens:20,cacheReadTokens:0,cacheMissTokens:100,billingProvider:'deepseek' as const}}
  await repo.persistModelCallSettlement(result,context)
  expect(await repo.listPendingModelCallSettlements('p-payments',{...context,userId:'other'})).toEqual([])
  const [pending]=await repo.listPendingModelCallSettlements('p-payments',context)
  expect(pending).toMatchObject({state:'completed',usage:{inputTokens:100,outputTokens:20}})
  await expect(repo.persistModelCallSettlement({...result,state:'cancelled'},context)).rejects.toThrow('immutable')
  await repo.settleModelCall(pending!,context)
  await repo.settleModelCall(result,context)
  expect(await repo.listPendingModelCallSettlements('p-payments',context)).toEqual([])
  expect((await repo.getTeamOverview(context)).projectCost.find(r=>r.key==='p-payments')?.totalTokens).toBe(priorTokens+120)
 })
 it('reserves simultaneous requests against the same remaining budget',async()=>{const cost=projectedModelCallCost(quote('x'))!;expect(cost).toBeGreaterThan(0);const repo=await setup(cost*1.5);const decisions=await Promise.all([repo.reserveModelCall(quote('one'),context),repo.reserveModelCall(quote('two'),context)]);expect(decisions.filter(d=>d.accepted)).toHaveLength(1);expect(decisions.filter(d=>d.decision.blocksRun)).toHaveLength(1)})
 it('uses the server billing month even when the client clock is in the past',async()=>{const cost=projectedModelCallCost(quote('x'))!;const repo=await setup(cost*1.5);expect((await repo.reserveModelCall({...quote('old-clock'),createdAt:'2026-08-01T00:00:00Z'},context)).accepted).toBe(true);expect((await repo.reserveModelCall(quote('current-clock'),context)).accepted).toBe(false)})
 it('keeps failed paid usage, deduplicates settlement despite JSON key order, and rejects changed settlement',async()=>{const repo=await setup();await repo.reserveModelCall(quote('one'),context);const settlement={id:'one',projectId:'p-payments',state:'failed' as const,usage:{inputTokens:100,outputTokens:20,cacheReadTokens:0,cacheMissTokens:100,cacheStatus:'complete' as const}};await repo.settleModelCall(settlement,context);await repo.settleModelCall({...settlement,usage:{outputTokens:20,inputTokens:100,cacheMissTokens:100,cacheReadTokens:0,cacheStatus:'complete' as const}},context);const row=(await repo.getTeamOverview(context)).budgetProjectCost!.find(r=>r.key==='p-payments')!;expect(row.totalTokens).toBe(120);expect(row.costUsd).toBeGreaterThan(0);await expect(repo.settleModelCall({...settlement,state:'not_sent'},context)).rejects.toThrow('immutable')})
 it('treats cancellation without usage as unknown and enforces a fresh cloud policy',async()=>{const repo=await setup();await repo.reserveModelCall(quote('one'),context);await repo.settleModelCall({id:'one',projectId:'p-payments',state:'cancelled'},context);expect(await repo.reserveModelCall(quote('two'),context)).toMatchObject({accepted:false,decision:{status:'unavailable'}});await repo.saveRuntimeBudgetPolicy({projectId:'p-payments',enabled:false,monthlyLimitUsd:50,warningThresholdUsd:40,currency:'USD',updatedAt:now},context);expect(await repo.reserveModelCall(quote('three'),context)).toMatchObject({accepted:true,decision:{status:'disabled'}})})
 it('counts historical chat metadata once without requiring a workflow Run',async()=>{const repo=await setup();const input={quote:quote('legacy-chat-one'),settlement:{id:'legacy-chat-one',projectId:'p-payments',state:'completed' as const,usage:{inputTokens:200,outputTokens:50,cacheReadTokens:0,cacheMissTokens:200}}};await repo.importHistoricalModelCall(input,context);await repo.importHistoricalModelCall(input,context);expect((await repo.getTeamOverview(context)).budgetProjectCost?.find(r=>r.key==='p-payments')?.totalTokens).toBe(250);await expect(repo.importHistoricalModelCall({...input,settlement:{...input.settlement,usage:{inputTokens:300,outputTokens:0}}},context)).rejects.toThrow('immutable');await expect(repo.importHistoricalModelCall(input,{...context,userId:'other'})).rejects.toThrow('scope')})
 it('consumes an exact scoped approval across multiple rounds instead of reusing its full allowance',async()=>{const cost=projectedModelCallCost(quote('x'))!;const repo=await setup(0);await repo.saveRuntimeBudgetApproval({id:'approval',projectId:'p-payments',providerId:'deepseek',requestedBy:context.userId,approvedBy:'u-erich',role:'owner',maxAdditionalCostUsd:cost*1.5,reason:'bounded fixture',status:'approved',createdAt:now,expiresAt:'2026-09-24T00:00:00Z'},context);expect(await repo.reserveModelCall({...quote('one'),approvalId:'approval'},context)).toMatchObject({accepted:true});expect(await repo.reserveModelCall({...quote('two'),approvalId:'approval'},context)).toMatchObject({accepted:false});await expect(repo.settleModelCall({id:'one',projectId:'p-payments',state:'not_sent'},{...context,userId:'other'})).rejects.toThrow('scope')})
 it('does not confuse another project’s evidence markers with the same consumption',()=>{const call={...quote('one'),userId:'u',state:'completed' as const,costUsd:1,projectedCostUsd:1};const row={id:'evidence',runId:'r',nodeId:'n',userId:'u',projectId:'other',provider:'openai' as const,model:'m',inputTokens:1,outputTokens:1,cacheReadTokens:0,costUsd:2,timestamp:now,budgetAttemptIds:['one']};expect(modelCallBudgetRollup([row],[call],now).find(r=>r.key==='other')?.costUsd).toBe(2);expect(()=>parseModelCallSettlement({id:'bad',projectId:'p',state:'completed',usage:{inputTokens:-1}})).toThrow()})
})
